---
# Install all the GUI Geoscripting software on Ubuntu-like OSs.

- name: Install geoscripting GUI software
  hosts: "{{ host | default('localhost') }}"
  become: yes
  vars:
    rstudio_version: 2025.05.1-513
    rstudio_branch: "{{ ubuntu_codename | default('jammy') }}"
    arch: "{{ system_arch | default('amd64') }}"

  tasks:
  - name: Display system information
    debug:
      msg:
        - "Installing on {{ arch }} architecture"
        - "Using Ubuntu codename: {{ rstudio_branch }}"
        - "RStudio version: {{ rstudio_version + ' (stable)' if arch == 'amd64' else 'Latest daily build' }} ({{ arch }})"

  - name: Gather package facts
    package_facts:
        manager: apt

  - name: Install GUI tools
    apt:
        name:
        - qgis
        - grass
        - saga
        - spatialite-gui
        - mesa-utils
        - spatialite-bin
        - git-gui
        - git-cola
        - oxygen-icon-theme
        - rkward
        - cmake

  - name: Make sure local applications path exists
    file:
      path: /usr/local/share/applications
      state: directory

  - name: Add Git GUI to the menu
    copy:
        src: ../common/git-gui.desktop
        dest: /usr/local/share/applications/git-gui.desktop

  - name: Get latest RStudio daily build info for ARM64
    uri:
      url: https://dailies.rstudio.com/rstudio/latest/index.json
      method: GET
      return_content: yes
    register: rstudio_daily_info
    when: arch == "arm64"

  - name: Install RStudio desktop (AMD64 - stable release)
    apt:
        deb: https://download1.rstudio.org/electron/{{ rstudio_branch }}/{{ arch }}/rstudio-{{ rstudio_version }}-{{ arch }}.deb
    when: arch == "amd64"

  - name: Install RStudio desktop (ARM64 - daily build)
    apt:
        deb: "{{ (rstudio_daily_info.content | from_json).products.electron.platforms[rstudio_branch + '-arm64'].link }}"
    when: arch == "arm64"

  - name: Fix RStudio sandbox permissions
    ansible.builtin.file:
        path: /usr/lib/rstudio/chrome-sandbox
        mode: '4755'

  - name: Add Google Earth repo key
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/linux_signing_key.pub
      dest: /etc/apt/trusted.gpg.d/google.asc
      mode: '0644'
      force: true


  - name: Install Google Earth (AMD64)
    apt:
        deb: https://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
    when: '"google-earth-pro-stable" not in ansible_facts.packages and arch == "amd64"'

  - name: Skip Google Earth installation on ARM64
    debug:
      msg: "Google Earth is not available for ARM64 architecture, skipping installation"
    when: arch == "arm64"


  - name: Add VSCode repo key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
      mode: '0644'
      force: true

  - name: Add VSCode repository
    apt_repository:
      repo: "deb [arch={{ arch }}] https://packages.microsoft.com/repos/vscode stable main"
      filename: vscode

  - name: Install VSCode
    apt:
        name: code
        update_cache: true
