---
# Install all the GUI Geoscripting software on Ubuntu-like OSs.

- name: Install geoscripting GUI software
  hosts: "{{ host | default('localhost') }}"
  become: yes
  vars:
    rstudio_version: 2025.05.1-513
    rstudio_branch: jammy

  tasks:
  - name: Gather package facts
    package_facts:
        manager: apt

  - name: Install GUI tools
    apt:
        name:
        - qgis
        - grass
        - saga
        - spatialite-gui
        - mesa-utils
        - spatialite-bin
        - git-gui
        - git-cola
        - oxygen-icon-theme
        - rkward

  - name: Make sure local applications path exists
    file:
      path: /usr/local/share/applications
      state: directory

  - name: Add Git GUI to the menu
    copy:
        src: ../common/git-gui.desktop
        dest: /usr/local/share/applications/git-gui.desktop

  - name: Install RStudio desktop
    apt:
        deb: https://download1.rstudio.org/electron/{{ rstudio_branch }}/amd64/rstudio-{{ rstudio_version }}-amd64.deb

  - name: Fix RStudio sandbox permissions
    ansible.builtin.file:
        path: /usr/lib/rstudio/chrome-sandbox
        mode: '4755'

  - name: Add Google Earth repo key
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/linux_signing_key.pub
      dest: /etc/apt/trusted.gpg.d/google.asc
      mode: '0644'
      force: true


  - name: Install Google Earth
    apt:
        deb: https://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
    when: '"google-earth-pro-stable" not in ansible_facts.packages'


  - name: Add VSCode repo key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
      mode: '0644'
      force: true

  - name: Add VSCode repository
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      filename: vscode

  - name: Install VSCode
    apt:
        name: code
        update_cache: true
