---
# Install software that is useful for servers.
- name: Install server software
  hosts: "{{ host | default('localhost') }}"
  become: yes
  
  tasks:
  - name: Enable SSH through firewall
    ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: Enable firewall
    ufw:
      state: enabled
            
  - name: Install server utils
    apt:
      name: ['tmux', 'htop', 'earlyoom', 'gnome-remote-desktop', 'winpr-utils', 'snapper', 'smartmontools', 'default-jre-headless', 'openssh-server']
      update_cache: yes

  - name: Configure earlyoom
    copy:
      src: earlyoom
      dest: /etc/default/earlyoom

  - name: Create extra earlyoom config
    file:
      path: /etc/systemd/system/earlyoom.service.d
      state: directory

  - name: Enable priority for earlyoom
    copy:
      src: earlyoom-priority.conf
      dest: /etc/systemd/system/earlyoom.service.d/earlyoom-priority.conf

  - name: Start earlyoom
    systemd:
      name: earlyoom
      state: restarted
      daemon_reload: yes
      enabled: yes

  - name: Enable RDP through firewall
    ufw:
      rule: allow
      port: "3389"
      proto: tcp

  - name: Enable RDP in the system
    shell: |
      grdctl --system rdp enable
      grdctl --system rdp set-credentials geoscripting geoscripting

  - name: Generate and install TLS certificate
    shell: |
      sudo -u gnome-remote-desktop winpr-makecert -silent -rdp -path ~gnome-remote-desktop rdp-tls
      grdctl --system rdp set-tls-key ~gnome-remote-desktop/rdp-tls.key
      grdctl --system rdp set-tls-cert ~gnome-remote-desktop/rdp-tls.crt
    creates: /var/lib/gnome-remote-desktop/rdp-tls.key

  - name: Start GNOME Remote Desktop
    service:
      name: gnome-remote-desktop
      state: restarted
      enabled: yes
