---
# Install software that is useful for virtual machines/servers.
- name: Install VM software
  hosts: "{{ host | default('localhost') }}"
  become: yes
  vars:
    rstudio_version: 2025.05.1-513
    rstudio_branch: jammy

  tasks:
  - name: Install RStudio Server
    apt:
      deb: https://download2.rstudio.org/server/{{ rstudio_branch }}/amd64/rstudio-server-{{ rstudio_version }}-amd64.deb

  - name: Enable RStudio Server through firewall
    ufw:
      rule: allow
      port: "8787"
      proto: tcp

  - name: Start RStudio Server
    service:
      name: rstudio-server
      state: started
      enabled: yes

  - name: Create shutdown disabler directory
    file:
      path: "/usr/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm"
      state: directory

  - name: Get shutdown disabler extension
    ansible.builtin.unarchive:
      src: https://github.com/pratap-panabaka/gse-bring-out-submenu-of-power-off-logout/archive/refs/heads/main.zip
      dest: /tmp/
      remote_src: yes
      creates: /tmp/gse-bring-out-submenu-of-power-off-logout-main/

  - name: Find shutdown disabler files
    find:
      paths: "/tmp/gse-bring-out-submenu-of-power-off-logout-main/src/v-45-46-47-48/"
      recurse: no
      patterns: "*.*"
    register: files_to_copy

  - name: Install shutdown disabler files
    copy:
      src: "{{ item.path }}"
      dest: "/usr/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/"
      remote_src: true
    with_items: "{{ files_to_copy.files }}"

  - name: Install shutdown disabler schema
    copy:
      src: "/tmp/gse-bring-out-submenu-of-power-off-logout-main/src/v-45-46-47-48/schemas/"
      remote_src: true
      dest: /usr/share/glib-2.0/schemas/

  - name: Compile glib schemas
    shell:
      chdir: /usr/share/glib-2.0/schemas
      cmd: glib-compile-schemas .

  - name: Create dconf profile
    copy:
      src: geoscripting
      dest: /etc/dconf/profile/geoscripting

  - name: Create dconf db directory
    file:
      path: /etc/dconf/db/geoscripting.d
      state: directory

  - name: Set shutdown button to disabled
    copy:
      src: 50-disable-shutdown
      dest: /etc/dconf/db/geoscripting.d/50-disable-shutdown

  - name: Enable dconf changes
    shell:
      cmd: dconf update

  - name: Set the geoscripting dconf profile
    copy:
      src: 50-geoscripting-dconf.sh
      dest: /etc/profile.d/50-geoscripting-dconf.sh

  - name: Clean up unneeded files
    file:
      path: /tmp/gse-bring-out-submenu-of-power-off-logout-main
      state: absent

  - name: Disable automatic updates
    copy:
      content: 'APT::Periodic::Unattended-Upgrade "0";'
      dest: /etc/apt/apt.conf.d/99disable-auto-upgrades
