---
- name: Install geoscripting CLI software
  hosts: localhost

  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    when: ansible_default_ipv4.gateway is defined

  - name: Print the gateway for each host when undefined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has no gateway
    when: ansible_default_ipv4.gateway is undefined

  - name: Print a parameter
    ansible.builtin.debug:
      msg: The parameter value is: "{{ test_dainius_param }}"
    when: test_dainius_param is defined

  - name: Print a parameter
    ansible.builtin.debug:
      msg: The parameter value is blank!
    when: test_dainius_param is undefined
