---
- name: Install geoscripting CLI software
  hosts: localhost

  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    when: ansible_default_ipv4.gateway is defined

  - name: Print the gateway for each host when undefined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    when: ansible_default_ipv4.gateway is undefined
