---
# Install ansible-galaxy via Ansible.
- name: Install Ansible Galaxy
  hosts: localhost
  become: yes

  tasks:
  - name: Install necessary collections
    command: ansible-galaxy collection install community.general community.postgresql

