---
# Install all the GUI Geoscripting software on Ubuntu-like OSs.

- name: Install geoscripting GUI software
  hosts: all
  become: yes
  vars:
    rstudio_version: 2021.09.0-351
    rstudio_branch: bionic

  tasks:
  - name: Install GUI tools
    apt:
        name:
        - qgis
        - grass
        - saga
        - spatialite-gui
        - mesa-utils
        - spatialite-bin
        - git-gui
        - git-cola
        - rkward
        - oxygen-icon-theme

  - name: Make sure local applications path exists
    file:
      path: /usr/local/share/applications
      state: directory

  - name: Add Git GUI to the menu
    copy:
        src: ../common/git-gui.desktop
        dest: /usr/local/share/applications/git-gui.desktop

  - name: Install RStudio desktop
    apt:
        deb: https://download1.rstudio.org/desktop/{{ rstudio_branch }}/amd64/rstudio-{{ rstudio_version }}-amd64.deb

  - name: Install Google Earth
    apt:
        deb: https://dl.google.com/dl/earth/client/current/google-earth-stable_current_amd64.deb
