---
# Install all the CLI Geoscripting software on Ubuntu-like OSs.
- name: Install geoscripting CLI software
  hosts: all
  become: yes

  tasks:
  - name: Install CLI utilities
    apt:
      name: gdal-bin
  
  - name: Install R and its package dependencies
    apt:
      name: ['r-base', 'r-base-dev', 'libgdal-dev', 'libgeos-dev', 'libproj-dev', 'libxml2-dev', 'libcurl4-openssl-dev', 'libssl-dev', 'libudunits2-dev']

  - name: Install PostGIS
    apt:
      name:
      - postgis
      - pgadmin3
      - postgresql-contrib
      - postgresql-server-dev-12
      - python3-psycopg2

  - name: Add geoscripting user to postgresql
    become_user: postgres
    community.general.postgresql_user:
      name: geoscripting
      password: geoscripting
      role_attr_flags: CREATEDB,NOSUPERUSER

  - name: Add new postgresql DB
    become_user: postgres
    community.general.postgresql_db:
      name: geoscripting

  - name: Enable PostGIS
    become_user: postgres
    community.general.postgresql_ext:
      name: postgis
      db: geoscripting

